version: "3.8"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8002:8002"
    volumes:
      - './:/app/'

networks:
    managia-network:
      driver: bridge

volumes:
    mongodb-data:
    mongodb-config:
    mongodb-init:
    mongodb-log:
    mongodb-etc:
    fastapi:

